Move aws skd pkgs to peer deps
shelfio/dynamodb-parallel-scan pull request #189
Opened 2022-07-18 07:36 UTC by Maksym-Haiovets

2022-07-18 07:42 UTC, vladgolubev approved these changes

2022-07-18 07:43 UTC, vladgolubev commented on package.json
> +    "@aws-sdk/lib-dynamodb": "3.x.x"
Move it from deps to devDeps

2022-07-18 07:43 UTC, vladgolubev requested changes
.

2022-07-18 07:46 UTC, vladgolubev approved these changes

2022-07-18 07:53 UTC, merged

2022-07-22 11:02 UTC, KnupMan approved these changes